version: '3'
services:
  php-fpm:
    build:
      context: services/php-fpm
      args:
        PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        TZ: "$TZ"
    container_name: php
    environment:
      # 檢測用
      - DB_ROOT_PWD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PWD=${MYSQL_PASSWORD}
    expose:
      - 9000
    extra_hosts:
      - "www.site1.com:172.17.0.1"
    volumes:
      - ${SOURCE_DIR}:/www/:cached
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${LOG_DIR}/php-fpm:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: unless-stopped
    tty: true
    cap_add:
      - SYS_PTRACE
    networks:
      - default
  nginx:
    build:
      context: services/nginx
      args:
        NGINX_VERSION: nginx:${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
    container_name: nginx
    volumes:
      - ${SOURCE_DIR}:/www:cached
      - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
      - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
      - ${LOG_DIR}/nginx:/var/log/nginx/:rw
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "8000:8000"
    restart: unless-stopped
    command: nginx -g 'daemon off;'
  mysql:
    build:
      context: services/mysql
      args:
        MYSQL_VERSION: mysql:${MYSQL5_VERSION}
        TZ: "$TZ"
    container_name: mysql
    tty: true
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
      - ${LOG_DIR}/mysql:/var/lib/mysql-logs:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "$TZ"
    restart: unless-stopped
    networks:
      - default
  redis:
      build: services/redis
      container_name: redis
      tty: true
      ports:
        - "${REDIS_HOST_PORT}:6379"
      volumes:
        - ./services/redis/redis.conf:/etc/redis/redis.conf:rw
        - ./data/redis:/data:rw
        - ./logs/redis:/var/log/:rw
      restart: unless-stopped
networks:
  default:
    driver: bridge